FROM oven/bun:1

WORKDIR /app

ARG DATABASE_LINK

COPY ./package.json ./package.json
COPY ./packages ./packages
COPY turbo.json .

COPY ./apps/web ./apps/web

RUN bun install
RUN bun install npm
RUN bun run db:generate 

RUN export DATABSE_URL=${DATABASE_LINK} && bun run build 

CMD ["bun", "run", "web:run"]

