name : docker push be
on : 
  push : 
    branches : [main]

run-name : docker push deployement be
jobs :
  build :
    runs-on : ubuntu-latest
    name : building mono-repo
    steps : 
      - name : "cloning the repo"
        uses : actions/checkout@v2
        with : 
          fetch-depth : 1
      - name : docker login
        uses : docker/login-action@v2
        with : 
          username : ${{secrets.DOCKERHUB_USERNAME}}
          password : ${{secrets.DOCKERHUB_TOKEN}}
      - name : build and push 
        uses : docker/build-push-action@v4
        with : 
          context : .
          file : ./docker/Dockerfile.be 
          push : true
          tags : atomiczeone/mono-be:${{github.sha}}
      - name : fetching the docker image in vm 
        run : | 
          mkdir /home/runner/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/.ssh/ssh_key
          cat ~/.ssh/ssh_key 
          chmod 600 /home/runner/.ssh/ssh_key
          ssh-keyscan -H ${{secrets.EC2_IP}} > ~/.ssh/known_hosts
          ssh -t -i ~/.ssh/ssh_key ${{secrets.EC2_HOST}} "which docker && docker stop user_backend && docker run --name user_backend -d -p 3000:3000 -e DATABASE_URL='${{secrets.DATABASE_LINK}}' 100xdevs/user-app-backend:${{ github.sha }}"