name : docker push fe
on : 
  push : 
    branches : [main]

run-name : docker push deployement fe 
jobs :
  build :
    runs-on : ubuntu-latest
    name : building mono-repo
    steps : 
      - name : "cloning the repo"
        uses : actions/checkout@v2
        with : 
          fetch-depth : 1
      - name : docker login
        uses : docker/login-action@v2
        with : 
          username : ${{secrets.DOCKERHUB_USERNAME}}
          password : ${{secrets.DOCKERHUB_TOKEN}}
      - name : check the database url 
        run : echo ${{secrets.DATABASE_LINK}}
      - name : build and push 
        uses : docker/build-push-action@v4
        with : 
          context : .
          file : ./docker/Dockerfile.fe
          build-args : | 
            DATABASE_LINK=${{secrets.DATABASE_LINK}}
          push : true
          tags : atomiczeone/mono-fe:${{github.sha}}